baseURL = "https://example.com/"
languageCode = "pt-br"
title = "Women Who Go Curitiba"
theme = "mediumish"
summaryLength = 25
copyright = "John Doe - All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="Comunidade de Golang de Curitiba"

[params.author]
  name = "Women Who Go Curitiba"
  thumbnail = "/images/logo.png"
  description = "A comunidade que vos fala"

[params.index]
  picture = "/images/logo.png"
  title = "Whomen Who Go Curitiba"
  subtitle = "✨ chapter de Curitiba do Women Who Go"
  mdtext = '''
💛 construindo uma comunidade de #golang mais diversa\
**ainda não sei o que colocar aqui.**\
### yeeeeey!
'''
  alertbar = false

[params.social]
  github = "womenwhogocwb"
  linkedin = "womenwhogocwb"
  twitter = "womenwhogocwb"
  instagram = "womenwhogocwb"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Sobre nós"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 200
    url = "/static/imprint"
